### ISSUE TITLE
Request for state description

### ISSUE THREAD

**Issue by WentseChen** [MichaelTMatthews/Craftax#11]
Hi Team,

Thank you for your excellent work. Could you please provide or direct me to a detailed explanation of each component in the environment's state, possibly through a .md file?

**Comment by MichaelTMatthews** [comment]
Hi Wentse, see I've added this to `obs_description.md`.  Let me know if that's sufficient!

**Comment by WentseChen** [comment]
Thank you very much for adding the details to the obs_description.md file. I appreciate your prompt and thorough assistance with this.
