### ISSUE TITLE
Data for expert gameplay

### ISSUE THREAD

**Issue by roger-creus** [MichaelTMatthews/Craftax#16]
Hi! 

In the paper, you mention:

`For perspective, it took one of the authors (with extensive knowledge of the game mechanics) roughly 5 hours of gameplay to first achieve a ‘perfect’ run where every achievement was completed. This was playing in a GUI that allowed for unlimited time to pause and think before taking each action.`

And I see the `play_craftax()` function records the trajectories of environment states, actions and rewards. Could you please release that data for the "perfect run" you mention in the paper?

Thank you! :)

**Comment by MichaelTMatthews** [comment]
Hi Roger, releasing a small offline dataset is on my TODO list - I'll let you know when it's released

**Comment by MichaelTMatthews** [comment]
@roger-creus please see the new offline dataset section in the README.  Unfortunately the subsequent refactors of the environment have made the pkl files invalid, but you can role back to v1.1.0 and it should all work.

Let me know if that works for you!

**Comment by roger-creus** [comment]
Hey! Re-opening this @MichaelTMatthews ! I have been able to call `render_craftax_pixels` but not `render_craftax_text` on all states in the dataset! I am using `craftax==1.1.0` as suggested for processing this data.

When rendering the text observations I get:

```
Traceback (most recent call last):
  text_obs = render_craftax_text(state)
  craftax/renderer.py", line 1062, in render_craftax_text
    text_obs += ItemType(item_map_view[x, y]).name.lower() + " on "
ValueError: Array(7, dtype=int32) is not a valid ItemType
```

How can I proceed? Thank you! :)
