### ISSUE TITLE
`play_craftax_classic` doesn't reset when the episode terminates

### ISSUE THREAD

**Issue by matomatical** [MichaelTMatthews/Craftax#18]
In `play_craftax.py`, [on lines 181--182](https://github.com/MichaelTMatthews/Craftax/blob/9ad9965a0e30feeb135d8acaf58d84e8b37b16fa/craftax/craftax/play_craftax.py#L181C1-L183C1), the script checks if the environment termination signal was returned by the step method, and so if the player reaches zero health the game ends.

In `play_craftax_classic.py`, [there is no such check](https://github.com/MichaelTMatthews/Craftax/blob/9ad9965a0e30feeb135d8acaf58d84e8b37b16fa/craftax/craftax_classic/play_craftax_classic.py#L121C1-L137C1), and indeed the player can continue to play with zero or negative health.

**Comment by MichaelTMatthews** [comment]
Thanks for finding and reporting this bug!
It should now be fixed in the latest commit
