### ISSUE TITLE
published packages include dev-only dependencies

### ISSUE THREAD

**Issue by garymm** [MichaelTMatthews/Craftax#29]
Consumers of craftax shouldn't pull in the dependencies that are only needed for development of craftax. Just from eye-balling the [pyproject.toml](https://github.com/MichaelTMatthews/Craftax/blob/91e558de60cb60c86855ad5e4ecb9fa801a8b174/pyproject.toml), I think at least these should be split into dev dependencies (or removed entirely since I can't find references to them in the code):
- argparse (included in all modern python versions by default)
- black
- orbax-checkpoint
- pre-commit
- wandb

**Comment by MichaelTMatthews** [comment]
Thanks for pointing out, resolved here https://github.com/MichaelTMatthews/Craftax/pull/30
